# Site settings
title: Michael Kostyatnikov
email: msk326@lehigh.edu
description: Sleep is optional, markets are eternal, and every challenge is just compound interest on character.
baseurl: "" # Empty because you're using a user/organization site
url: "https://michaelmsk326.github.io"
author: Michael Kostyatnikov
street_address: Scarsdale
city: New York
state: NY
zip_code: 10583
country: United States of America
phone: (646) 370-0618
icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
linkedin_url: https://www.linkedin.com/in/mkostyatnikov/

# Build settings
markdown: kramdown
sass:
  style: compressed
